<?php
// $Id: flat_book.install,v 1.1 2010/07/09 23:41:08 criticalpatch Exp $
/**
 * @file
 * install file for flat_book.
 * creates default persistant variables.
 */

/**
 * Implementation of hook_uninstall().
 * Delete settings variables.
 */
function flat_book_uninstall() {
  variable_del('flat_book_max_menu_depth');
  variable_del('flat_book_display_book_navigation');
  variable_del('flat_book_block_mode');
}
